mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include('portfolio.urls')),
    path('users/', include('users.urls')),
]

mysite/portfolio/urls.py
from django.urls import path
from .import views


app_name='portfolio'

urlpatterns=[
    path('', views.bongani_portfolio, name='bongani_portfolio')
    
]

mysite/users/urls.py
from django.urls import path
from .import views


app_name='users'

urlpatterns=[
    path('', views.user_login, name='user_login'),
    path('user_create/', views.user_create, name='user_create'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('validate_user/', views.validate_user, name='validate_user')
]

mysite/portfolio/models.py
from django.db import models

# Create your models here.

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

mysite/portfolio/views.py
from django.shortcuts import render

# Create your views here.

def bongani_portfolio(request):

    """
    Request bongani_portfolio
    
    :param: Request object
    :type: HttpRequest

    :return: bongani.html
    :rtype: HttpResponse

    """
    return render(request,'bongani.html')

mysite/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login

from django.contrib.auth import logout
from django.shortcuts import redirect

from django.contrib.auth.models import User

def user_login(request):

    """
        This displays users login form or user profile, if user is logged in.
        Request user_login
    
        :param: Request object
        :type: HttpRequest

        :return: user_login/ user_profile
        :rtype: HttpResponse

    """
    if request.user.is_authenticated:
        current_user = request.user
        return render(request, 'user_profile.html', {'current_user': current_user})
    else:
        current_user = None
        return render(request, 'user_login.html')
    
def validate_user(request):

    """
        To validate user login or user credentials
        Request validate_user
    
        :param: Request object
        :type: HttpRequest

        :return: user_login / user_profile
        :rtype: HttpResponse

    """
    email = request.POST['username']
    password = request.POST['password']    
    # Authorize user
    user = authenticate(username=email, password=password)
    # User is NOT Authenticated
    if user is None:
        # Update result parameter to pass to view
        error_message = "Invalid Username or Password!"
        # Construct reverse URL for Http Response Redirect
        return render(request, 'user_login.html', {'error_message': error_message})
    else:
        # Login user 
        login(request, user)
        return HttpResponseRedirect(reverse('users:user_profile'))
    
def user_profile(request):

    
    """
        Displays user profile if user is logged in
        Request user_profile
    
        :param: Request.user object
        :type: HttpRequest

        :return: user_profile
        :rtype: HttpResponse

    """
    print(request.user.username)
    if request.user.is_authenticated:
        return render(request, 'user_profile.html', {   
            "firstname": request.user.first_name,
            "lastname": request.user.last_name,
            "email": request.user.username, })
    else:
        return HttpResponseRedirect(reverse('users:user_login'))

def user_create(request):

    """
        Displays user registration form if user is logged in
        Request user_create
    
        :param: Request object
        :type: HttpRequest

        :return: user_profile/ user_create
        :rtype: HttpResponse

    """
    if request.method == 'POST':
        first_name = request.POST.get('firstname')
        last_name = request.POST.get('lastname')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirmpassword')

        # Create a New User & Save to Database
        try:
            if password == confirm_password:                
                user = User.objects.create_user(username=email, password=password)
                user.first_name = first_name
                user.last_name = last_name                                            
                user.is_staff = False
                user.is_superuser = False
                # Save user to Db
                user.save()
                # Redirect user
                return HttpResponseRedirect(reverse('users:user_profile'))

        except Exception as ex:
                print(f'SOMETHING WENT WRONG!\nError:\n{str(ex)}')
                return render(request, 'user_create.html', {'error': str(ex)})
    else:
         return render(request, 'user_create.html')

def user_logout(request):

    """
        Logs out user
        Request user_logout
    
        :param: Request object
        :type: HttpRequest

        :return: user_login
        :rtype: HttpResponse

    """
    logout(request)
    return HttpResponseRedirect(reverse('users:user_login'))
    

mysite/portfolio/templates/bongani.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
    <!--Head Resources-->
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <!--Web-page Title-->
        <title>{% block title %} Bongani Cacambile - Portfolio{% endblock %}</title>
        
        <!--Load Static Resources-->
        {% load static %}
        
        <!--Bootstrap CDN-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous" />
    </head>

    <!--Body-->
    <body class="p-2 m-0 border-0">
        <!--Header-->
        <header class="container-fluid mb-2 ms-1">
            <div class="row g-2">
                <div class="col">
                    <!--Application Name-->
                    <p class="fs-2">
                        Bongani Cacambile's Portfolio Application
                    </p>
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:user_profile' %}" class="btn btn-outline-primary">Profile</a>
                        <a href="{% url 'users:user_logout' %}" class="btn btn-outline-secondary">Logout</a>
                    {% else %}
                        <p>You are not logged in!</p>
                        <a href="{% url 'users:user_login' %}" class="btn btn-outline-primary">Login</a>
                        <a href="{% url 'users:user_create' %}" class="btn btn-outline-secondary">Register</a>            
                    {% endif %}
                </div>
            </div>
            <hr>            
        </header>
        
        <!--Biography-->
        <div class="container-fluid">
            <div class="bg-secondary-subtle bg-gradient border-dark rounded p-2">
                <div class="row g-2">
                    <!--Profile-->
                    <div class="col">
                        <img src="{% static 'media/GDTT.png' %}" title="Profile Picture"
                            class="img-fluid rounded-pill mt-3 ms-3 mb-3" height="250" width="250">
                    </div>
                    <!--Content-->
                    <div class="col">
                        <h5 class="fs-2 fw-bold text-white">About me</h5>
                        <!--First Paragraph-->
                        <p class="card-text fs-6 lead text-white">
                            My full name is Bongani Cacambile, I have a code B advanced drivers license, a Peace Officer and Traffic Warden Certificate that, I have completed in the Metro Police College in Cape Town Observatory. I have firearm license qualifications in Hand Gun, Hand Gun Business, Shot Gun, Shot Gun Business and also in Military and Law.
                            I have been privileged enough to work and be seconded with a really great Unit like the Metro Police GDTT (Gang and Drug Task Team), Metro Police K-9 Unit, Traffic and S.I.U (Special investigative Unit).
                            
                        </p>
                        <!--Second Paragraph-->
                        <p class="card-text fs-6 text-white">
                            The Stabilisation Unit enforces By-Laws and creates peace and order within a certain area of Jurisdiction and protects Council property especially against Gang violence or Gang infested areas. This is done by conducting stop and searches, house searches and VCP’s (Vehicle Inspections) via “Shot-Spotter” Joint operations with the GDTT, K-9, S.I.U, and Traffic and sometimes accompanied by SAPS (POPS) and OPS Combat. 

                            
                        </p>
                        <!--Third Paragraph-->
                        <p class="card-text fs-6 text-white">
                            I hope the above impresses and I look forward to the possible opportunity of an interview with you.

                            
                        </p>
                        <p class="card-text">
                            <small class="text-body-secondary">
                                Portfolio Application - Django Capstone Project
                            </small>
                        </p>
                    </div>
                </div>
            </div>
        </div>      

        <footer class="container-fluid">
            <hr>
            <p class="fs-5 fw-light text-secondary-emphasis">&copy; 2023 Bongani Cacambile. All rights reserved.</p>
        </footer>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    </body>
</html>

mysite/users/templates/shared/base.html
<!DOCTYPE html>
<!--_Layout File Starts-->
<html lang="en" data-bs-theme="dark">

<!--Resources-->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!--Render Page Title(Default)-->
    <title>{% block title %}Capstone Project - Users{% endblock %}</title>
    
    <!--Static Folder Served Directly(client)-->
    {% load static %}
    
    <!--(API)GCP WebFont's-->
    <link href="https://fonts.googleapis.com/css?family=Lato:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;display=swap" rel="stylesheet" />
    
    <!--(CDN)Bootstrap-v5.3.0-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous" />
    
    <!--Some Custom Styling-->
    <style>
        /* Custom CSS for the fixed footer */
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            padding: 10px 0;
        }
    </style>
</head>

<!--Body-->
<body class="p-3 m-0 border-0">

    <!--Header Container-->
    <header class="container-fluid mb-3 ms-0">
        <nav class="navbar bg-body-primary">            
            <div class="row g-2">
                <div class="col-12">
                    <p class="display-2">
                        {% block app_name %}Default App Name{% endblock %}
                    </p>
                </div>
                {% if user.is_authenticated %}
                <div class="col">
                    <a href="{% url 'users:user_profile' %}">Account</a>
                    <a href="{% url 'users:user_logout' %}">Logout</a>               
                </div>
                {% else %}                
                <div class="col">
                    <a href="{% url 'users:user_login' %}">Login</a>
                    <a href="{% url 'users:user_create' %}">Sign Up</a>                 
                </div>
                {% endif %}
            </div>
        </nav>
        <hr>
    </header>    

    <!--Main Container-->
    <main class="container-fluid">
        <!--Render View-->
        {% block content %}{% endblock %}
    </main>

    <!--Footer Container-->
    <footer class="container-fluid footer">
        <hr>
        <p class="fs-5 fw-light text-secondary-emphasis">&copy; 2023 Bongani Cacambile. All rights reserved.</p>
    </footer>

    <!--(CDN)Bootstrap-v5.3.0-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    
    <!--(CDN)JQuery-v3.6.0-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!--_Layout File Ends-->
</body></html>

mysite/users/templates/user_create.html
<!--Fetch_Layout File-->
{% extends 'shared/base.html' %}

<!--Set_Layout Application Name-->
{% block app_name %}
<!--Form Bootstrap SVG Icon-->
Register <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-key-fill"
    viewBox="0 0 16 16">
    <path
        d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
</svg>
{% endblock %}

<!--Set_Layout Page Title-->
{% block title %}Login{% endblock %}

{% block content %}

<div class="container">
    <form href="{% url 'users:user_create' %}" class="form-control" method="post">
        {% csrf_token %}
        <div class="row g-2 align-item-center">
            
            <div class="col-12">
                <p class="fs-2">Register User</p>
            </div>

            <div class="col-6">
                <label class="form-label" for="firstname">First Name</label>
                <input type="text" class="form-control" name="firstname" placeholder="First Name" required>
            </div>

            <div class="col-6">
                <label class="form-label" for="lastname">Last Name</label>
                <input type="text" class="form-control" name="lastname" placeholder="Last Name" required>
            </div>

            <div class="col-6">
                <label class="form-label" for="Email">Email Address</label>
                <input type="email" class="form-control" name="email" placeholder="Email Address" required>
            </div>

            <div class="col-6">
                <label class="form-label" for="Phone">Contact Number</label>
                <input type="text" class="form-control" name="phone" placeholder="Contact Number" required>
            </div>

            <div class="col-6">
                <label class="form-label" for="password">Password</label>
                <input type="password" class="form-control" name="password" placeholder="Password" required>
            </div>

            <div class="col-6">
                <label class="form-label" for="confirm password">Confirm Password</label>
                <input type="password" class="form-control" name="confirmpassword" placeholder="Confirm Password"
                    required>
            </div>

            <div class="col-12">
                <input type="submit" value="Register" class="btn btn-outline-info">
            </div>

        </div>
    </form>
</div>
{% endblock %}

mysite/users/templates/user_login.html
<!--Fetch_Layout File-->
{% extends 'shared/base.html' %}

<!--Set_Layout Application Name-->
{% block app_name %}
<!--Form Bootstrap SVG Icon-->
Login <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-key-fill" viewBox="0 0 16 16">
    <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
</svg>
{% endblock %}

<!--Set_Layout Page Title-->
{% block title %}Login - [Custom App]{% endblock %}

<!--Body Content-->
{% block content %}
<div class="container">
    {% if user.is_authenticated %}
        <p class="display-5">You are already logged in!</p>
        <a class="btn btn-outline-primary mb-3" href="{% url 'users:user_logout' %}">Logout?</a>
        <a class="btn btn-outline-primary mb-3" href="{% url 'users:user_profile' %}">View Profile?</a>
    {% else %}
        <!--Login Form-->
        <form action="{% url 'users:validate_user' %}" class="form-control align-items-center" method="post">
            {% csrf_token %}            
            <div class="row g-3 align-items-center">
                <!--Form Title-->
                <div class="col-12">            
                    <p class="fs-4 fw-medium">Login using your username</p>                    
                </div>
                <!--Logic for Invalid User Credentials-->
                {% if error_message %}
                    <div class="col-12">
                        <p class="cite text-danger-emphasis">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-asterisk" viewBox="0 0 16 16">
                            <path d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z"/>
                        </svg> {{ error_message }}
                        <p class="bolder text-secondary"><em>You can try again or <a href="#ADD-URL-HERE">Create User</a></em></p>
                    </p>
                    
                    </div>
                {% endif %}

                <!--Username Input-->
                <div class="col-12">
                    <label class="form-label" for="username">Username</label>
                    <input type="text" class="form-control" name="username" placeholder="Username" required>
                </div>

                <!--Password Input-->
                <div class="col-12">
                    <label class="form-label" for="password">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="**********" required>
                </div>

                <!--Submit & Register Btn's-->
                <div class="col-12">
                    <div class="row g-3 align-items-center">
                        <div class="col">    
                            <input type="submit" class="btn btn-outline-info mb-3" value="Login" />
                            <a class="btn btn-outline-primary mb-3" href="{% url 'users:user_create' %}" title="Create New User">Create User?</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    {% endif %}
</div>
<!--Login Page Content Ends-->
{% endblock %}

mysite/users/templates/user_profile.html
<!--Fetch_Layout File-->
{% extends 'shared/base.html' %}

<!--Set_Layout Application Name-->
{% block app_name %}
<!--Form Bootstrap SVG Icon-->
Welcome Back, {{ firstname }}
{% endblock %}

<!--Set_Layout Page Title-->
{% block title %}User Account{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row g-2">
        <div class="col">
            <p class="fs-3 mb-0">First & Last Name</p>
            <p class="fs-4 ms-0">{{ firstname }} {{ lastname }}</p>
        </div>
        <div class="col">
            <p class="fs-3 mb-0">Email Address</p>
            <p class="fs-4 ms-0">{{ email }}</p>
        </div>     
        <div class="col">
            <a href="#0" class="btn btn-outline-danger">Delete Account</a>
        </div>
    </div>
</div>
{% endblock %}